Add Form Object, Set LocalStorage and Display Data
RaoAkif/Portfolio pull request #17
Opened 2022-03-03 21:23 UTC by RaoAkif

To Set Form Data as Object in Local Storage for Form:
- Add Form Object,
- Set Object data as Local Storage,
- Display Data in Form

2022-03-03 22:38 UTC, medaminedev66 requested changes
Hi @RaoAkif and @davidobi😃, :wave:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

_See the inline comments below for more required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 22:38 UTC, medaminedev66 commented on main.js
> +
- [ ] Following the project requirement, all entered values (Name, Email, Message) should be saved in the browser (local storage) after filling the form, and not submitting it. If the user reloads the page or closes the browser and opens it again, the form inputs should be auto-populated with the values entered in the previous visit to the page. Check out the requirements below 👇: 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/77190203/156664582-3c49c3e0-e314-48f9-b321-41c92c59dd8c.png">

2022-03-04 20:00 UTC, RaoAkif commented on main.js
> +
@medaminedev66 I have spent many hours on this small issue. But I am unable to implement this. 
Kindly help me out by sharing material or some instances that how can I achieve this functionality.

2022-03-04 22:46 UTC, keroloussamy requested changes
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-04 22:46 UTC, keroloussamy commented on main.js
> +});
- [ ] Until now your code is saving the data to the local storage, Now we need to when the user reload the page the data get displayed from the local storage inside the inputs. 

You can do that by 
```
window.onload = () => {
  let savedFormData = localStorage.getItem('user');
  savedFormData = JSON.parse(savedFormData);
  // Check if the form data object is found on localStorage
  if (savedFormData) {
  // populate inputs values if data was found
  // ex: nameInput.value = savedFormData.name
  }
};

 ```

You will get the data from local storage and put them inside every input. So when the user loads the page again if there's data saved in local storage it will be displayed.

2022-03-04 23:50 UTC, Donard97 approved these changes
## Hi @RaoAkif , 👋 

_Well done on implementing requested changes by other reviewers 👏 💯_  

_**Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:**_ 

## Congratulations! 🎉 🎉 🎉 

![giphy (6)](https://user-images.githubusercontent.com/74506933/156857087-78a87e93-900a-4dc6-8758-8bc3744a1170.gif)

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-05 00:08 UTC, merged