Header section mobile version
RaoAkif/Portfolio pull request #2
Opened 2022-02-10 01:27 UTC by RaoAkif

I have created the mobile version of Template 3 of my portfolio. I am having issue regarding the **rays.svg** 
This **rays.svg** (in images/icons) does not display. Either it hides itself, or covers the whole header and hero menu.
Kindly give suggestions regarding this also.

2022-02-10 02:58 UTC, keroloussamy requested changes
Hi @RaoAkif, 

Good job so far, you did great work until now 💯 🎉!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 02:58 UTC, keroloussamy commented on index.html
> +      </div>
For this part and your issue with rays.svg, you can extract the whole image instead of get every one separately. By select the whole image and extract 

![image](https://user-images.githubusercontent.com/35535130/153326294-3745f94d-dd55-42c4-a61f-f34224860d71.png)

<br><br><br>

Here is the whole background 
![header-illsutration-mobile](https://user-images.githubusercontent.com/35535130/153326388-140437e6-15e4-4f2f-987f-18a04fbfe43d.png)

<br>
And you can also extract it as SVG if you want.

2022-02-10 02:58 UTC, keroloussamy commented on index.html
> +          <h2>Welcome</h2>
Kindly your logo should be inside the `a` tag, so anyone who clicks on it switches him to the index/home page.
`<a herf="index.html">Welcome</a>`

2022-02-10 02:58 UTC, keroloussamy commented on index.html
> +        <div class="navbar-list">
Kindly use the `nav` tag instead of the `div` tag, it's more semantic.

2022-02-10 02:58 UTC, keroloussamy commented on index.html
> +        </div>
Kindly this is a list so it's more semantic to use `ul` tag to group them instead of `div`, and `li` per icon, and each icon has a link (`a` tag).
Like
```
<ul>
     <li><a href=".."><img  ...></a></li>
      ......
</ul>
```

2022-02-10 02:58 UTC, keroloussamy commented on index.html
> +      </div>
Kindly add the button at the last of the section.

This one

![image](https://user-images.githubusercontent.com/35535130/153321944-eb987cab-2e0a-4a37-b3d6-e06755fe7324.png)

2022-02-10 02:58 UTC, keroloussamy commented on main.css
> +  font-family: "Muli", sans-serif;
Kindly make the background color white as the Figma design.

2022-02-10 02:58 UTC, keroloussamy commented on index.html
> +        <img id="background-tile3" src="./images/icons/background-tile3.svg" alt="tile3">
Kindly change the images because they make wide right space out of the design.

Your design 
![image](https://user-images.githubusercontent.com/35535130/153328316-79eb5d2b-6ea8-4576-91a1-5a146e3c30f9.png)

Figma design 
![image](https://user-images.githubusercontent.com/35535130/153328388-1e528ad0-3a13-4010-9f83-2cd72ef5aecd.png)

2022-02-10 15:19 UTC, RaoAkif commented on index.html
> +      </div>
Thanks a lot, for this suggestion. I wasted 2 hours on this only.

2022-02-10 15:20 UTC, RaoAkif commented on index.html
> +          <h2>Welcome</h2>
Placed an image logo in it

2022-02-10 15:22 UTC, RaoAkif commented on index.html
> +        <div class="navbar-list">
OK. Done it.

2022-02-10 16:11 UTC, RaoAkif commented on index.html
> +        </div>
Done in this way:
<li><a href="linkedin.com/in/raoakif"><img src="./images/icons/linkedin.svg" alt="linkedin-icon" /></a></li>

2022-02-10 16:13 UTC, RaoAkif commented on index.html
> +      </div>
@keroloussamy 
I have wasted a lot of time on this small task. Kindly guide me, how to put this little button icon.

2022-02-10 16:15 UTC, RaoAkif commented on index.html
> +        <img id="background-tile3" src="./images/icons/background-tile3.svg" alt="tile3">
Yup. I have tried to resolve this issue, as you suggested.

2022-02-11 02:17 UTC, AnselemOdims requested changes
### Hi @RaoAkif, 
Good job on implementing some of the changes requested by the previous reviewer.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!. You can use the tag @AnselemOdims for a quicker reply.

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-11 02:17 UTC, AnselemOdims commented on main.css
> +  background-position-x: 25px;
- [ ] [OPTIONAL] Since this image only relates to the headline section. You can remove it from the body and put it in the headline section and then give it a background-position of center or cover, so it fills the full section.

2022-02-11 02:17 UTC, AnselemOdims commented on main.css
> +  font-family: "Muli", sans-serif;
- [ ] [OPTIONAL]  It will be more adequate to use all font specifications as specified in the design.

2022-02-11 02:17 UTC, AnselemOdims commented on index.html
> +      </div>
- [ ] Kindly include the button as pointed out by the previous reviewer. You can wrap in a an anchor tag and then put it inside a div tag. Thereafter, you can center the div in your stylesheet.

2022-02-11 02:18 UTC, AnselemOdims requested changes
### Hi @RaoAkif, 
Good job on implementing some of the changes requested by the previous reviewer.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!. You can use the tag @AnselemOdims for a quicker reply.

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-11 03:17 UTC, keroloussamy commented on index.html
> +      </div>
Hello @RaoAkif you can download the image from the Figma design, and put it inside `a` tag 

Like 
```
</a>
     <img src="the image" alt="" />
</a>
```


Here is the Image if you didn't find it
![Disabled](https://user-images.githubusercontent.com/35535130/153532415-5a6c5c1d-3260-47dc-8e18-412ba94d1a72.png)

2022-02-11 15:06 UTC, RaoAkif commented on main.css
> +  background-position-x: 25px;
I have to do this changing, but the issue is that header is very small, While hero section starts from down a little bit from the header. So I think, next time, I would always, create some section, that contains both, in some smart way.

2022-02-11 15:20 UTC, RaoAkif commented on main.css
> +  font-family: "Muli", sans-serif;
OK. So I have added the 
font-family: 'Roboto', sans-serif;
which comes under **Inter**
https://fonts.google.com/specimen/Inter
If I have done it wrong, kindly inform me @AnselemOdims

2022-02-11 15:52 UTC, RaoAkif commented
@keroloussamy @AnselemOdims  Kindly look at the changes, I have done. Big thanks to both of you !!!

2022-02-11 15:54 UTC, RaoAkif commented on index.html
> +      </div>
Yeah, thought about it. And found it earlier. Thanks for the suggestion.

2022-02-11 19:22 UTC, keroloussamy commented
@RaoAkif To review your code you have to submit it from your dashboard. Please make sure that you have implemented all the required changes before you submit.

2022-02-11 21:00 UTC, Donard97 approved these changes
## Hi @RaoAkif , 👋  

_Good job on implementing the requested changes from the other reviewers! 💯 👍_ 

**Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:** 

## Congratulations! 🎉

![giphy (7)](https://user-images.githubusercontent.com/74506933/153669546-b79d775d-9b9f-489c-be9a-5bcd0f46d34d.gif)

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-11 21:14 UTC, merged