Desktop Version Changes
RaoAkif/Portfolio pull request #6
Opened 2022-02-18 21:11 UTC by RaoAkif

2022-02-18 23:35 UTC, keroloussamy requested changes
Hi @RaoAkif, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 23:35 UTC, keroloussamy commented on main.css
> +  margin-left: 12px;
- [ ] Kindly remove the `margin-right: 12px; margin-left: 12px;` because they make overflow in your desktop.

- [ ] And at the parent with `.portfolios` class, please remove the width and the margin and change `row-gap: 25px` to `gap: 15px`.

https://github.com/RaoAkif/Portfolio/blob/024a6a22e9ffde0fbde60e870cb44f235008141a/main.css#L199-L204

All that to solve the overflow problem.

2022-02-18 23:35 UTC, keroloussamy commented on main.css
>    background-position-y: 15px;
- [ ] Kindly the second background is not at the right place, you can use this [Link](https://www.w3schools.com/css/css3_backgrounds.asp) to see how to set to background positions.
![image](https://user-images.githubusercontent.com/35535130/154773442-15c34f68-cff3-46b6-93a3-23306e6609f0.png)

2022-02-18 23:35 UTC, keroloussamy commented on main.css
> +  }
- [ ] Kindly the line is not taking all the page width, that's because the `width: 1500px;` is applied for a specific number. it should be `width: 100%`.

- [ ] You have to solve the width with the parent with id `contact-message`, I will leave a comment on it.

2022-02-18 23:35 UTC, keroloussamy commented on main.css
> +
- [ ] Kindly remove the `width: 81.25%;  margin: auto;` and don't use them in all sections just when you need to set a specific width, I think you have this issue in all sections.

2022-02-18 23:35 UTC, keroloussamy commented on main.css
> +  background-position-x: 260px;
- [ ] Kindly reset the positions for the images and there are 3 images, not one. and don't use specific width with px because that's will fit in one position and the rest not.
![image](https://user-images.githubusercontent.com/35535130/154774473-069bc75f-3b7a-42c7-ac52-9590f528db94.png)

2022-02-18 23:35 UTC, keroloussamy commented on main.css
> +  }
- [ ] Kindly fix your background here, you can delete the `height: 152vh;` and add `background-size: cover;`
![image](https://user-images.githubusercontent.com/35535130/154774709-3b0a803f-5b3f-4884-a7f8-e4c3d854a362.png)

2022-02-19 00:04 UTC, RaoAkif commented on main.css
> +    background-image: url("./images/bg/Header-llustration-desktop.svg");
I have replaced a 700px with 990px

2022-02-19 00:15 UTC, RaoAkif commented on main.css
> +  margin-left: 12px;
Thanks a lot. It solved the issue.

2022-02-19 00:23 UTC, RaoAkif commented on main.css
>    background-position-y: 15px;
I have changed the code. But I am having the issues on other screens. 
Currents this is how it looks like.
![Capture](https://user-images.githubusercontent.com/61361037/154777722-c6671261-96f4-4e6f-9590-a107e81a3d9f.PNG)
![Capture1](https://user-images.githubusercontent.com/61361037/154777723-8f4cc068-4cb5-4d2a-a097-9ff53a1e764f.PNG)

2022-02-19 00:25 UTC, RaoAkif commented on main.css
> +  }
OK. Thanks

2022-02-19 01:55 UTC, RaoAkif commented on main.css
> +
@keroloussamy 
Please give me clear guidance. I have spent 2 hours on this specific comment. But Could not apply the background on this section.
Either let it go. Or tell me how can I put the background on both mobile and desktop view, correctly.

2022-02-19 11:51 UTC, keroloussamy commented on main.css
> +  background-position-x: 260px;
@RaoAkif you can do it like `background-image:  url(......), url(......), url(......);` and set the position like `background-position: 0 78%, 21% 75%, 100% 61%;` and change the numbers as fits on your site.

2022-02-19 12:02 UTC, keroloussamy commented on main.css
> +
@RaoAkif you need to make the line take the whole width, and because this parent takes the width 81.25% so the line not taking the whole width like in the pic.
![image](https://user-images.githubusercontent.com/35535130/154799852-ef31d0ef-a44d-4a63-a8cf-afcff1096431.png)

So you can remove the `width: 81.25%; margin: auto;` from `#contact-message` and put them in the child with id `#footer-top`.

2022-02-19 12:04 UTC, keroloussamy commented on main.css
>    background-position-y: 15px;
@RaoAkif it's fine with the mob version, but you need to play with the positions to make it a little top (the left image) in the desktop version.

2022-02-19 12:05 UTC, keroloussamy commented on main.css
>    background-position-y: 15px;
@RaoAkif you can delete the `background-position-y: 15px;` and just use the `background-position` for the two images.

2022-02-19 13:25 UTC, RaoAkif commented on main.css
> +  background-position-x: 260px;
Wow. Just wow. This has worked perfectly in almost every section. Thanks for this suggestion @keroloussamy

2022-02-19 13:27 UTC, RaoAkif commented on main.css
> +  }
I have revised this section. The desktop version is fine now. Thanks for pointing out. I was actually missing few components in the background, but was not noticing. Thanks

2022-02-19 15:28 UTC, RaoAkif commented on main.css
> +
I have removed the widths of containers and margin: auto. But I have applied on each elements with respect to the mobile and desktop version. It's working perfectly fine. Kindly look at it. If there is any suggestion to improve.
Kindly be specific abut comments. Thanks

2022-02-19 16:08 UTC, medaminedev66 approved these changes
# Hi @RaoAkif , 

### Status: Approved ✔️

:+1: You have implemented all the suggestions. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


**You may close this Pull Request and merge the changes**

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Amine Smahi_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 16:08 UTC, medaminedev66 commented on main.css
> +  }
[OPTIONAL] It would be better to align the buttons of the projects at the same position to improve the your UI design:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/77190203/154808647-83111ac0-b781-4249-9c2e-4174e397c0eb.png">

2022-02-21 16:50 UTC, merged