Adding Accessibility
RaoAkif/Portfolio pull request #9
Opened 2022-02-22 19:51 UTC by RaoAkif

Changed the title

2022-02-22 19:52 UTC, TesheMaximillan commented
### Accessibility 

- **Page titles** - A little modification on the title is made
- **Image text alternatives** - no issues found
- **Text headings** - no issues found
- **Color contrast** - no issues found
- **Resize** - no issues found
- **Interaction** - no issues found
- **Moving content** - no issues found
- **Multimedia** - no issues found
- **The basic structure of the page** - no issues found

2022-02-22 20:07 UTC, micheaol requested changes
Hi Team , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-22 20:07 UTC, micheaol commented on index.html
>    <body>
**Contrast ratio ("color contrast")**:

* Please ensure that the page has a minimum contrast ratio of at least 4.5:1 for normal-size text. Please check the contest report [HERE](https://www.aditus.io/button-contrast-checker/rawcdn-githack-com-2022-02-22-at-19-59-45-959?failing)

2022-02-22 20:07 UTC, micheaol commented on index.html
>        gtag('config', 'G-2TBWY4L6YS');
Please ensure that every form control has a label associated with it using 'label', 'for', and 'id' according to the project requirement.

2022-02-22 22:38 UTC, RaoAkif commented on index.html
>    <body>
Hi @micheaol,
I have tried many times to achieve the color contrast, but due to change of extremely different background color or font color,
the figma design becomes completely different, and will change the requirements of the project.

2022-02-22 22:40 UTC, RaoAkif commented on index.html
>        gtag('config', 'G-2TBWY4L6YS');
In the project requirements, it was clearly stated, to **remove** font labels etc. and give placeholder to its input.

2022-02-22 22:41 UTC, RaoAkif commented on index.html
>        gtag('config', 'G-2TBWY4L6YS');
So, what to do, in this case?

2022-02-22 22:55 UTC, micheaol commented on index.html
>        gtag('config', 'G-2TBWY4L6YS');
@RaoAkif, for accessibility for and for the project requirement. Kindly add 'label'

2022-02-24 11:09 UTC, RaoAkif commented on index.html
>        gtag('config', 'G-2TBWY4L6YS');
@micheaol 
I have added **label** as you suggested. But I have done one thing:
- I have added Accessible hiding CSS class in the label div, so that the website become accessible  
- This approach will also preserve the design provided to us.

**Reference:** [Accessible hiding CSS class](https://a11y-guidelines.orange.com/en/web/components-examples/accessible-hiding/#:~:text=Sometimes%20it%20is%20necessary%20to,also%20for%20screen%20reader%20users.&text=For%20this%2C%20an%20accessible%20hiding%20CSS%20class%20can%20be%20used.)

2022-02-24 11:50 UTC, keroloussamy approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-28 13:32 UTC, merged